# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('start_work_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_work_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания работы')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name_plural': 'профили',
                'verbose_name': 'профиль',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'отделы',
                'verbose_name': 'отдел',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Sector', verbose_name='Отдел'),
        ),
    ]
